trigger:
  branches:
    include:
      - Dev

resources:
  repositories:
    - repository: self

variables:
  dockerRegistryServiceConnection: 'DockerHubServiceConnection'
  imageRepository: 'nipuniofficial/repo_1'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  helmChartPath: 'charts/compose-integration'
  pool: 'Local-Windows-Agent'
  namespace: 'compose'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool: $(pool)
        steps:
          - script: |
              set JAVA_HOME=C:\Program Files\Java\jdk-17
              set PATH=%JAVA_HOME%\bin;%PATH%
              java -version
            displayName: Set Java 17 as the default version

          - task: Gradle@3
            inputs:
              gradleWrapperFile: 'gradlew'
              options: 'bootjar'
              tasks: 'bootjar'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              javaHomeOption: 'Path'
              jdkUserInputPath: 'C:\Program Files\Java\jdk-17'
              sonarQubeRunAnalysis: false
              spotBugsAnalysis: false

          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

          - task: PublishBuildArtifacts@1
            displayName: Publish Helm chart as artifact
            inputs:
              PathtoPublish: '$(helmChartPath)'
              ArtifactName: 'helm-chart'
              publishLocation: 'Container'
