apiVersion: v1
kind: Secret
metadata:
  name: compose-integration-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AZURE_KEYVAULT_URI: "{{ .Values.env.AZURE_KEYVAULT_URI }}"
  AZURE_KEYVAULT_TENANT_ID: "{{ .Values.env.AZURE_KEYVAULT_TENANT_ID }}"
  AZURE_KEYVAULT_CLIENT_ID: "{{ .Values.env.AZURE_KEYVAULT_CLIENT_ID }}"
  AZURE_KEYVAULT_CLIENT_SECRET: "{{ .Values.env.AZURE_KEYVAULT_CLIENT_SECRET }}"
  NEW_RELIC_LICENSE_KEY: "{{ .Values.env.NEW_RELIC_LICENSE_KEY }}"
